`ifndef FAULT_ANALYZER_TB_DEFINES_VH
`define FAULT_ANALYZER_TB_DEFINES_VH

`define TB_CLK_PERIOD_NS 10
`define TB_RESET_CYCLES 5
`define TB_TIMEOUT_CYCLES 10000

`define TB_EXPECTED_GOWIN_IDCODE 32'h0120_681B
`define TB_JTAG_IDCODE_OPCODE 8'h11
`define TB_FIFO_EVENT_WIDTH 64
`define TB_FIFO_EVENT_DEPTH 64
`define TB_UART_BAUD 115200
`define TB_JTAG_TCK_HZ 2000000
`define TB_VGA_H_ACTIVE 640
`define TB_VGA_V_ACTIVE 480

`endif
